#include "InventoryItemWidget.h"
#include "Components/Image.h"
#include "Blueprint/WidgetTree.h"
#include "Blueprint/DragDropOperation.h"
#include "Blueprint/WidgetBlueprintLibrary.h"
#include "InventoryWidget.h"
#include "InventoryComponent.h"
#include "BackToZaraysk/Characters/BTZBaseCharacter.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/Border.h"
#include "Components/Button.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "BackToZaraysk/GameData/Items/Test/PickupCube.h"
#include "BackToZaraysk/GameData/Items/Test/PickupParallelepiped.h"
#include "BackToZaraysk/Inventory/EquippableItemData.h"
#include "BackToZaraysk/Components/EquipmentComponent.h"
#include "BackToZaraysk/Characters/PlayerCharacter.h"
#include "BackToZaraysk/GameData/Items/TacticalVest.h"

void UInventoryItemWidget::Init(UInventoryItemData* InData, UTexture2D* InIcon, const FVector2D& CellSize)
{
    ItemData = InData;
    SizeX = InData ? FMath::Max(1, InData->SizeInCellsX) : 1;
    SizeY = InData ? FMath::Max(1, InData->SizeInCellsY) : 1;
    if (!Image && WidgetTree)
    {
        Image = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("Icon"));
        this->SetClipping(EWidgetClipping::ClipToBounds);
        this->WidgetTree->RootWidget = Image;
    }
    if (Image)
    {
        UTexture2D* Icon = InIcon ? InIcon : ((InData && InData->Icon) ? InData->Icon : LoadObject<UTexture2D>(nullptr, TEXT("/Engine/EngineResources/WhiteSquareTexture.WhiteSquareTexture")));
        FSlateBrush Brush; Brush.SetResourceObject(Icon); Brush.ImageSize = FVector2D(CellSize.X * SizeX, CellSize.Y * SizeY);
        Image->SetBrush(Brush);
    }
}

void UInventoryItemWidget::NativeConstruct()
{
    Super::NativeConstruct();
    bIsFocusable = true; // –ø–æ–∑–≤–æ–ª—è–µ–º –ª–æ–≤–∏—Ç—å R –Ω–∞ –≤–∏–¥–∂–µ—Ç–µ –ø—Ä–µ–¥–º–µ—Ç–∞
    SetVisibility(ESlateVisibility::Visible);
    SetIsEnabled(true);
}

FReply UInventoryItemWidget::NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    const FKey Button = InMouseEvent.GetEffectingButton();
    if (Button == EKeys::RightMouseButton)
    {
        if (UInventoryWidget* Parent = GetTypedOuter<UInventoryWidget>())
        {
            if (UCanvasPanel* Root = Cast<UCanvasPanel>(Parent->WidgetTree->RootWidget))
            {
                // –£–¥–∞–ª—è–µ–º –ø—Ä–µ–¥—ã–¥—É—â–µ–µ –º–µ–Ω—é
                TArray<UWidget*> Children = Root->GetAllChildren();
                for (UWidget* W : Children)
                {
                    if (W && W->GetFName() == TEXT("ContextMenu"))
                    {
                        Root->RemoveChild(W);
                        break;
                    }
                }
                UBorder* Menu = Parent->WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("ContextMenu"));
                Menu->SetBrushColor(FLinearColor(0.f,0.f,0.f,0.9f));
                Menu->SetPadding(FMargin(8.f));
                
                if (GEngine)
                {
                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Yellow, 
                        FString::Printf(TEXT("üîç Creating context menu for item: %s"), 
                            ItemData ? *ItemData->DisplayName.ToString() : TEXT("null")));
                }
                
                // –ö–æ–Ω—Ç–µ–π–Ω–µ—Ä –¥–ª—è –≤–µ—Ä—Ç–∏–∫–∞–ª—å–Ω–æ–≥–æ —Å—Ç–µ–∫–∞ –∫–Ω–æ–ø–æ–∫
                UVerticalBox* VBox = Parent->WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("ContextMenuVBox"));
                Menu->SetContent(VBox);

                // –ö–Ω–æ–ø–∫–∏ –¥–ª—è —ç–∫–∏–ø–∏—Ä—É–µ–º—ã—Ö –ø—Ä–µ–¥–º–µ—Ç–æ–≤
                UEquippableItemData* EquippableItem = Cast<UEquippableItemData>(ItemData);
                if (ItemData && EquippableItem)
                {
                    // –ü—Ä–æ–≤–µ—Ä—è–µ–º, —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω –ª–∏ –ø—Ä–µ–¥–º–µ—Ç
                    if (EquippableItem->bIsEquipped)
                    {
                        // –°–Ω—è—Ç—å
                        UButton* UnequipBtn = Parent->WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
                        UTextBlock* UnequipTxt = Parent->WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                        UnequipTxt->SetText(FText::FromString(TEXT("–°–Ω—è—Ç—å")));
                        UnequipBtn->AddChild(UnequipTxt);
                        VBox->AddChildToVerticalBox(UnequipBtn);
                        // –î–ª—è —Ä—é–∫–∑–∞–∫–∞ –≤ —Å–ª–æ—Ç–µ –¥–µ–ª–∞–µ–º –∫–Ω–æ–ø–∫—É –Ω–µ–∞–∫—Ç–∏–≤–Ω–æ–π –∏ –≤–∏–∑—É–∞–ª—å–Ω–æ —Ç—É—Å–∫–ª–æ–π
                        if (EquippableItem->EquipmentSlot == Backpack)
                        {
                            UnequipBtn->SetIsEnabled(false);
                            UnequipBtn->SetRenderOpacity(0.5f);
                            UnequipTxt->SetColorAndOpacity(FLinearColor(0.6f, 0.6f, 0.6f, 0.7f));
                        }
                        UnequipBtn->OnClicked.Clear();
                        UnequipBtn->OnClicked.AddDynamic(this, &UInventoryItemWidget::OnUnequipClicked);
                    }
                    else
                    {
                        // –ù–∞–¥–µ—Ç—å
                        UButton* EquipBtn = Parent->WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
                        UTextBlock* EquipTxt = Parent->WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                        EquipTxt->SetText(FText::FromString(TEXT("–ù–∞–¥–µ—Ç—å")));
                        EquipBtn->AddChild(EquipTxt);
                        VBox->AddChildToVerticalBox(EquipBtn);
                        EquipBtn->OnClicked.Clear();
                        EquipBtn->OnClicked.AddDynamic(this, &UInventoryItemWidget::OnEquipClicked);
                    }
                }
                
                // –ö–Ω–æ–ø–∫–∞ "–í—ã–±—Ä–æ—Å–∏—Ç—å"
                {
                UButton* DropBtn = Parent->WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
                UTextBlock* Txt = Parent->WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                    Txt->SetText(FText::FromString(TEXT("–í—ã–±—Ä–æ—Å–∏—Ç—å")));
                    Txt->SetColorAndOpacity(FLinearColor::White);
                DropBtn->AddChild(Txt);
                    VBox->AddChildToVerticalBox(DropBtn);
                    DropBtn->OnClicked.Clear();
                    DropBtn->OnClicked.AddDynamic(this, &UInventoryItemWidget::OnDropClicked);
                }
                
                if (GEngine)
                {
                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Yellow, TEXT("üîç Added Drop button to context menu"));
                }
                if (UCanvasPanelSlot* S = Root->AddChildToCanvas(Menu))
                {
                    const FVector2D ScreenPos = InMouseEvent.GetScreenSpacePosition();
                    const FVector2D Local = Root->GetCachedGeometry().AbsoluteToLocal(ScreenPos);
                    S->SetAnchors(FAnchors(0.f,0.f,0.f,0.f));
                    S->SetAlignment(FVector2D(0.f,0.f));
                    S->SetPosition(Local + FVector2D(6.f,6.f));
                    S->SetSize(FVector2D(220.f, 200.f));
                    S->SetZOrder(9999);
                }
            }
        }
        return FReply::Handled();
    }
    if (Button == EKeys::LeftMouseButton)
    {
        // –ó–∞–ø—É—Å–∫–∞–µ–º drag —á–µ—Ä–µ–∑ DetectDragIfPressed (–æ–Ω –≤—ã–∑–æ–≤–µ—Ç NativeOnDragDetected)
        return UWidgetBlueprintLibrary::DetectDragIfPressed(InMouseEvent, this, EKeys::LeftMouseButton).NativeReply;
    }
    return Super::NativeOnMouseButtonDown(InGeometry, InMouseEvent);
}

void UInventoryItemWidget::OnDropClicked()
{
    if (UInventoryWidget* Parent = GetTypedOuter<UInventoryWidget>())
    {
        if (!ItemData) return;
        
        APlayerController* PC = Parent->GetOwningPlayer();
        if (!PC) return;
        
        APlayerCharacter* PlayerChar = Cast<APlayerCharacter>(PC->GetPawn());
        if (!PlayerChar || !PlayerChar->InventoryComponent) return;
        
        UInventoryComponent* InvComp = PlayerChar->InventoryComponent;
        bool bItemRemoved = false;

        // –ï—Å–ª–∏ –ø—Ä–µ–¥–º–µ—Ç —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω –∏ —ç—Ç–æ —Ä—é–∫–∑–∞–∫ ‚Äî —Å–Ω–∏–º–∞–µ–º –∏ –≤—ã–±—Ä–∞—Å—ã–≤–∞–µ–º –≤ –º–∏—Ä
        if (UEquippableItemData* EquippableItem = Cast<UEquippableItemData>(ItemData))
        {
            if (EquippableItem->bIsEquipped && EquippableItem->EquipmentSlot == Backpack)
            {
                if (InvComp->UnequipItemToInventory(Backpack, true))
                {
                    bItemRemoved = true;
                    // –û–±–Ω–æ–≤–ª—è–µ–º UI —ç–∫–∏–ø–∏—Ä–æ–≤–∫–∏ –∏ –≥—Ä–∏–¥ —Ä—é–∫–∑–∞–∫–∞
                    Parent->UpdateEquipmentSlots();
                    Parent->UpdateBackpackStorageGrid();
                }
            }
        }
        
        // –ü—Ä–æ–≤–µ—Ä—è–µ–º, —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω –ª–∏ –ø—Ä–µ–¥–º–µ—Ç
        UEquippableItemData* EquippableItem = Cast<UEquippableItemData>(ItemData);
        if (EquippableItem && EquippableItem->bIsEquipped)
        {
            // –°–Ω–∏–º–∞–µ–º —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –ø—Ä–µ–¥–º–µ—Ç –∏ –≤—ã–±—Ä–∞—Å—ã–≤–∞–µ–º –µ–≥–æ
            if (InvComp->UnequipItemToInventory(EquippableItem->EquipmentSlot, true))
            {
                bItemRemoved = true;
                if (GEngine)
                {
                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Orange, 
                        FString::Printf(TEXT("üóëÔ∏è –≠–∫–∏–ø–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –ø—Ä–µ–¥–º–µ—Ç %s —Å–Ω—è—Ç –∏ –≤—ã–±—Ä–æ—à–µ–Ω"), *ItemData->DisplayName.ToString()));
                }
            }
        }
        else
        {
            // –û–±—ã—á–Ω—ã–π –ø—Ä–µ–¥–º–µ—Ç –∏–∑ –∏–Ω–≤–µ–Ω—Ç–∞—Ä—è
            if (InvComp->RemoveSpecificFromBackpack(ItemData))
            {
                bItemRemoved = true;
                if (GEngine)
                {
                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Orange, 
                        FString::Printf(TEXT("üóëÔ∏è –ü—Ä–µ–¥–º–µ—Ç %s —É–¥–∞–ª–µ–Ω –∏–∑ –∏–Ω–≤–µ–Ω—Ç–∞—Ä—è –∏ –≤—ã–±—Ä–æ—à–µ–Ω"), *ItemData->DisplayName.ToString()));
                }
            }
        }
        
        if (bItemRemoved)
        {
            // –°–ø–∞–≤–Ω–∏–º –ø—Ä–µ–¥–º–µ—Ç –ø–µ—Ä–µ–¥ –∏–≥—Ä–æ–∫–æ–º
            FVector ViewLoc; FRotator ViewRot; PC->GetPlayerViewPoint(ViewLoc, ViewRot);
                            const FVector SpawnLoc = ViewLoc + ViewRot.Vector() * 80.f;
            FActorSpawnParameters S; 
            S.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;
            
                            // –û–ø—Ä–µ–¥–µ–ª—è–µ–º Pickup-–∫–ª–∞—Å—Å —á–µ—Ä–µ–∑ –µ–¥–∏–Ω—ã–π –º–∞–ø–ø–µ—Ä
                            extern TSubclassOf<AActor> GetPickupClassForItem_Internal(const UInventoryItemData* ItemData);
                            TSubclassOf<AActor> DropClass = GetPickupClassForItem_Internal(ItemData);
            
                            if (UWorld* World = GetWorld())
                            {
                                World->SpawnActor<AActor>(DropClass, SpawnLoc, ViewRot, S);
            }
            
            // –û–±–Ω–æ–≤–ª—è–µ–º UI (–ø—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ)
            Parent->RefreshInventoryUI();
            
            // –£–¥–∞–ª—è–µ–º –≤–∏–¥–∂–µ—Ç –ø—Ä–µ–¥–º–µ—Ç–∞
            Parent->RemoveItemWidget(this);
            Parent->RemoveItemMapping(ItemData);
        }
        
        // –ó–∞–∫—Ä—ã—Ç—å –º–µ–Ω—é
        if (UCanvasPanel* RootLocal = Cast<UCanvasPanel>(Parent->WidgetTree->RootWidget))
        {
            TArray<UWidget*> Children2 = RootLocal->GetAllChildren();
            for (UWidget* W2 : Children2)
            {
                if (W2 && W2->GetFName() == TEXT("ContextMenu"))
                {
                    RootLocal->RemoveChild(W2);
                    break;
                }
            }
        }
    }
}

void UInventoryItemWidget::OnEquipClicked()
{
    if (!ItemData) 
    {
        if (GEngine) GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, TEXT("‚ùå ItemData is null"));
        return;
    }
    
    UEquippableItemData* EquippableItem = Cast<UEquippableItemData>(ItemData);
    if (!EquippableItem) 
    {
        if (GEngine) GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, 
            FString::Printf(TEXT("‚ùå ItemData is not UEquippableItemData. Class: %s"), 
                ItemData ? *ItemData->GetClass()->GetName() : TEXT("null")));
        return;
    }
    
    // –ü–æ–ª—É—á–∞–µ–º PlayerCharacter
    if (UInventoryWidget* Parent = GetTypedOuter<UInventoryWidget>())
    {
        APlayerController* PC = Parent->GetOwningPlayer();
        if (PC)
        {
            APlayerCharacter* PlayerChar = Cast<APlayerCharacter>(PC->GetPawn());
            if (PlayerChar && PlayerChar->InventoryComponent)
            {
                if (GEngine)
                {
                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Green, 
                        FString::Printf(TEXT("‚úÖ PlayerCharacter found, InventoryComponent: %s"), 
                            PlayerChar->InventoryComponent ? TEXT("OK") : TEXT("NULL")));
                }
                
                UInventoryComponent* InvComp = PlayerChar->InventoryComponent;
                
                // –≠–∫–∏–ø–∏—Ä—É–µ–º –ø—Ä–µ–¥–º–µ—Ç
                if (InvComp->EquipItemFromInventory(EquippableItem))
                {
                    if (GEngine)
                    {
                        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Green, 
                            FString::Printf(TEXT("‚úÖ –≠–∫–∏–ø–∏—Ä–æ–≤–∞–Ω–æ: %s"), *EquippableItem->DisplayName.ToString()));
                    }
                    
                    // –û—á–∏—â–∞–µ–º –ø–æ–∑–∏—Ü–∏—é –ø—Ä–µ–¥–º–µ—Ç–∞ –∏–∑ —Å–∏—Å—Ç–µ–º—ã drag & drop
                    Parent->ClearItemPosition(EquippableItem);
                    
                    // –û–±–Ω–æ–≤–ª—è–µ–º UI
                    Parent->SyncBackpack(InvComp->BackpackItems);
                    
                    // –ü—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ–±–Ω–æ–≤–ª—è–µ–º –≥—Ä–∏–¥—ã –ø–æ—Å–ª–µ —ç–∫–∏–ø–∏—Ä–æ–≤–∫–∏ (—Å –Ω–µ–±–æ–ª—å—à–æ–π –∑–∞–¥–µ—Ä–∂–∫–æ–π)
                    FTimerHandle TimerHandleEquip;
                    UInventoryWidget* ParentWidgetEquip = Parent;
                    GetWorld()->GetTimerManager().SetTimer(TimerHandleEquip, [ParentWidgetEquip, EquippableItem]()
                    {
                        if (ParentWidgetEquip)
                        {
                            if (EquippableItem->EquipmentSlot == Vest)
                            {
                                ParentWidgetEquip->UpdateVestGrid();
                                if (GEngine)
                                {
                                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Cyan, TEXT("üîÑ –ü—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ–±–Ω–æ–≤–ª–µ–Ω –≥—Ä–∏–¥ –∂–∏–ª–µ—Ç–∞ –ø–æ—Å–ª–µ —ç–∫–∏–ø–∏—Ä–æ–≤–∫–∏"));
                                }
                            }
                            else if (EquippableItem->EquipmentSlot == Backpack)
                            {
                                // Backpack grid removed - no longer needed
                                if (GEngine)
                                {
                                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Cyan, TEXT("üîÑ –†—é–∫–∑–∞–∫ —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω (–≥—Ä–∏–¥ —É–¥–∞–ª–µ–Ω)"));
                                }
                            }
                        }
                    }, 0.1f, false);
                }
                else
                {
                    if (GEngine)
                    {
                        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, 
                            TEXT("‚ùå –ù–µ —É–¥–∞–ª–æ—Å—å —ç–∫–∏–ø–∏—Ä–æ–≤–∞—Ç—å –ø—Ä–µ–¥–º–µ—Ç"));
                    }
                }
            }
        }
    }
    
    // –ó–∞–∫—Ä—ã—Ç—å –º–µ–Ω—é
    if (UInventoryWidget* Parent = GetTypedOuter<UInventoryWidget>())
    {
        if (UCanvasPanel* RootLocal = Cast<UCanvasPanel>(Parent->WidgetTree->RootWidget))
        {
            TArray<UWidget*> Children2 = RootLocal->GetAllChildren();
            for (UWidget* W2 : Children2)
            {
                if (W2 && W2->GetFName() == TEXT("ContextMenu"))
                {
                    RootLocal->RemoveChild(W2);
                    break;
                }
            }
        }
    }
}

void UInventoryItemWidget::OnUnequipClicked()
{
    if (!ItemData) 
    {
        if (GEngine) GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, TEXT("‚ùå ItemData is null"));
        return;
    }
    
    UEquippableItemData* EquippableItem = Cast<UEquippableItemData>(ItemData);
    if (!EquippableItem) 
    {
        if (GEngine) GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, 
            FString::Printf(TEXT("‚ùå ItemData is not UEquippableItemData. Class: %s"), 
                ItemData ? *ItemData->GetClass()->GetName() : TEXT("null")));
        return;
    }
    
    // –ü–æ–ª—É—á–∞–µ–º PlayerCharacter
    if (UInventoryWidget* Parent = GetTypedOuter<UInventoryWidget>())
    {
        APlayerController* PC = Parent->GetOwningPlayer();
        if (PC)
        {
            APlayerCharacter* PlayerChar = Cast<APlayerCharacter>(PC->GetPawn());
            if (PlayerChar && PlayerChar->InventoryComponent)
            {
                UInventoryComponent* InvComp = PlayerChar->InventoryComponent;
                
                // –°–Ω–∏–º–∞–µ–º –ø—Ä–µ–¥–º–µ—Ç
                if (InvComp->UnequipItemToInventory(EquippableItem->EquipmentSlot, false))
                {
                    if (GEngine)
                    {
                        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Green, 
                            FString::Printf(TEXT("‚úÖ –°–Ω—è—Ç–æ: %s"), *EquippableItem->DisplayName.ToString()));
                        
                        // –î–∏–∞–≥–Ω–æ—Å—Ç–∏–∫–∞ —Ä–∞–∑–º–µ—Ä–∞ —Ä—é–∫–∑–∞–∫–∞ –ø–µ—Ä–µ–¥ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ–º UI
                        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Cyan, 
                            FString::Printf(TEXT("üîç Backpack size before UI update: %d"), InvComp->BackpackItems.Num()));
                        
                        // –ü—Ä–æ–≤–µ—Ä—è–µ–º, –µ—Å—Ç—å –ª–∏ –ø—Ä–µ–¥–º–µ—Ç –≤ —Ä—é–∫–∑–∞–∫–µ
                        if (InvComp->BackpackItems.Contains(EquippableItem))
                        {
                            GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Green, 
                                TEXT("‚úÖ Item found in backpack after unequip"));
                        }
                        else
                        {
                            GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, 
                                TEXT("‚ùå Item NOT found in backpack after unequip"));
                        }
                        
                        // –ü—Ä–æ–≤–µ—Ä—è–µ–º —Ñ–ª–∞–≥ bIsEquipped
                        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Cyan, 
                            FString::Printf(TEXT("üîç Item bIsEquipped flag: %s"), EquippableItem->bIsEquipped ? TEXT("true") : TEXT("false")));
                    }
                    
                    // –ü—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ—á–∏—â–∞–µ–º —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É—é—â–∏–µ UI –∑–æ–Ω—ã
                    if (EquippableItem->EquipmentSlot == Vest)
                    {
                        if (GEngine)
                        {
                            GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, TEXT("üóëÔ∏è –°–Ω—è—Ç –∂–∏–ª–µ—Ç - –ø—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ—á–∏—â–∞–µ–º –≥—Ä–∏–¥—ã"));
                        }
                        Parent->ForceClearVestGrids();
                    }
                    else if (EquippableItem->EquipmentSlot == Backpack)
                    {
                        // –î–ª—è —Ä—é–∫–∑–∞–∫–∞: –ø—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –ø—Ä—è—á–µ–º/—É–¥–∞–ª—è–µ–º –µ–≥–æ –≥—Ä–∏–¥
                        if (GEngine)
                        {
                            GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, TEXT("üóëÔ∏è –°–Ω—è—Ç —Ä—é–∫–∑–∞–∫ - —Å–∫—Ä—ã–≤–∞–µ–º –≥—Ä–∏–¥ —Ö—Ä–∞–Ω–∏–ª–∏—â–∞"));
                        }
                        Parent->UpdateEquipmentSlots();
                        Parent->UpdateBackpackStorageGrid();
                    }
                    
                    // –ü—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ—á–∏—â–∞–µ–º –≥—Ä–∏–¥ —Ä—é–∫–∑–∞–∫–∞ –ø—Ä–∏ —Å–Ω—è—Ç–∏–∏ —Ä—é–∫–∑–∞–∫–∞
                    if (EquippableItem->EquipmentSlot == Backpack)
                    {
                        if (GEngine)
                        {
                            GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, TEXT("üóëÔ∏è –°–Ω—è—Ç —Ä—é–∫–∑–∞–∫ - –ø—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ—á–∏—â–∞–µ–º –≥—Ä–∏–¥"));
                        }
                        
                        // Backpack grid removed - no longer needed
                    }
                    
                    // –û–±–Ω–æ–≤–ª—è–µ–º UI
                    Parent->RefreshInventoryUI();
                    
                    // –î–ª—è –¥—Ä—É–≥–∏—Ö –ø—Ä–µ–¥–º–µ—Ç–æ–≤ (–Ω–µ –∂–∏–ª–µ—Ç –∏ –Ω–µ —Ä—é–∫–∑–∞–∫) –ø—Ä–æ—Å—Ç–æ –æ–±–Ω–æ–≤–ª—è–µ–º –≥—Ä–∏–¥—ã
                    if (EquippableItem->EquipmentSlot != Vest && EquippableItem->EquipmentSlot != Backpack)
                    {
                        // –î–ª—è –¥—Ä—É–≥–∏—Ö –ø—Ä–µ–¥–º–µ—Ç–æ–≤ –ø—Ä–æ—Å—Ç–æ –æ–±–Ω–æ–≤–ª—è–µ–º –≥—Ä–∏–¥—ã
                        FTimerHandle TimerHandle;
                        UInventoryWidget* ParentWidget = Parent;
                        GetWorld()->GetTimerManager().SetTimer(TimerHandle, [ParentWidget]()
                        {
                            if (ParentWidget)
                            {
                                ParentWidget->UpdateVestGrid();
                                // Backpack grid removed - no longer needed
                                if (GEngine)
                                {
                                    GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Cyan, TEXT("üîÑ –ü—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω–æ –æ–±–Ω–æ–≤–ª–µ–Ω –≥—Ä–∏–¥ –∂–∏–ª–µ—Ç–∞ –ø–æ—Å–ª–µ —Å–Ω—è—Ç–∏—è"));
                                }
                            }
                        }, 0.1f, false);
                    }
                }
                else
                {
                    if (GEngine)
                    {
                        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, 
                            TEXT("‚ùå –ù–µ —É–¥–∞–ª–æ—Å—å —Å–Ω—è—Ç—å –ø—Ä–µ–¥–º–µ—Ç"));
                    }
                }
            }
        }
    }
    
        // –ó–∞–∫—Ä—ã—Ç—å –º–µ–Ω—é
    if (UInventoryWidget* Parent = GetTypedOuter<UInventoryWidget>())
    {
        if (UCanvasPanel* RootLocal = Cast<UCanvasPanel>(Parent->WidgetTree->RootWidget))
        {
            TArray<UWidget*> Children2 = RootLocal->GetAllChildren();
            for (UWidget* W2 : Children2)
            {
                if (W2 && W2->GetFName() == TEXT("ContextMenu"))
                {
                    RootLocal->RemoveChild(W2);
                    break;
                }
            }
        }
    }
}

FReply UInventoryItemWidget::NativeOnKeyDown(const FGeometry& InGeometry, const FKeyEvent& InKeyEvent)
{
    if (InKeyEvent.GetKey() == EKeys::R && ItemData && ItemData->bRotatable)
    {
        // –ü–µ—Ä–µ–¥–∞–µ–º –æ–±—Ä–∞–±–æ—Ç–∫—É –≤—Ä–∞—â–µ–Ω–∏—è —Ä–æ–¥–∏—Ç–µ–ª—å—Å–∫–æ–º—É –≤–∏–¥–∂–µ—Ç—É –∏–Ω–≤–µ–Ω—Ç–∞—Ä—è
        if (UInventoryWidget* ParentInv = GetTypedOuter<UInventoryWidget>())
        {
            // –£—Å—Ç–∞–Ω–∞–≤–ª–∏–≤–∞–µ–º —Å–µ–±—è –∫–∞–∫ hovered item –¥–ª—è –∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ–π –æ–±—Ä–∞–±–æ—Ç–∫–∏
            ParentInv->SetHoveredItem(this);
            return ParentInv->HandleItemRotation(InGeometry, InKeyEvent);
        }
        
        // Fallback: –ª–æ–∫–∞–ª—å–Ω–∞—è –æ–±—Ä–∞–±–æ—Ç–∫–∞ –µ—Å–ª–∏ —Ä–æ–¥–∏—Ç–µ–ª—å –Ω–µ –Ω–∞–π–¥–µ–Ω
        bRotated = !bRotated;
        UpdateVisualSize(FVector2D(60.f, 60.f));
        return FReply::Handled();
    }
    return Super::NativeOnKeyDown(InGeometry, InKeyEvent);
}

void UInventoryItemWidget::NativeOnDragDetected(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent, UDragDropOperation*& OutOperation)
{
    // –†–∞–∑—Ä–µ—à–∞–µ–º –Ω–æ—Ä–º–∞–ª—å–Ω—ã–π drag –¥–∞–∂–µ –µ—Å–ª–∏ –ø—Ä–µ–¥–º–µ—Ç –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ –≥—Ä–∏–¥–µ ‚Äî
    // –ø–µ—Ä–µ–Ω–æ—Å/—É–¥–∞–ª–µ–Ω–∏–µ –æ–±—Ä–∞–±–æ—Ç–∞–µ–º –Ω–∞ —Å—Ç–∞–¥–∏–∏ Drop
    UDragDropOperation* Op = UWidgetBlueprintLibrary::CreateDragDropOperation(UDragDropOperation::StaticClass());
    if (Op)
    {
        UInventoryItemWidget* DragVisual = CreateWidget<UInventoryItemWidget>(GetOwningPlayer(), UInventoryItemWidget::StaticClass());
        if (DragVisual)
        {
            UTexture2D* IconTex = (ItemData && ItemData->Icon)
                ? ItemData->Icon
                : LoadObject<UTexture2D>(nullptr, TEXT("/Engine/EngineResources/WhiteSquareTexture.WhiteSquareTexture"));
            DragVisual->Init(ItemData, IconTex, FVector2D(60.f, 60.f));
            DragVisual->bRotated = bRotated;
            DragVisual->UpdateVisualSize(FVector2D(60.f, 60.f));
            DragVisual->SetTint(FLinearColor(1.f, 1.f, 1.f, 0.85f));
            DragVisual->SetVisibility(ESlateVisibility::HitTestInvisible);
            Op->DefaultDragVisual = DragVisual;
        }
        Op->Payload = this;
        Op->Pivot = EDragPivot::MouseDown;
        OutOperation = Op;
    }
    // –ü–æ–¥—Å–≤–µ—Ç–∫–∞ –∏—Å—Ö–æ–¥–Ω–æ–≥–æ –≤–∏–¥–∂–µ—Ç–∞
    SetTint(FLinearColor(1.f, 1.f, 0.f, 1.f));
}

void UInventoryItemWidget::NativeOnMouseEnter(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    Super::NativeOnMouseEnter(InGeometry, InMouseEvent);
    if (UInventoryWidget* ParentInv = GetTypedOuter<UInventoryWidget>())
    {
        ParentInv->SetHoveredItem(this);
    }
}

void UInventoryItemWidget::NativeOnMouseLeave(const FPointerEvent& InMouseEvent)
{
    Super::NativeOnMouseLeave(InMouseEvent);
    if (UInventoryWidget* ParentInv = GetTypedOuter<UInventoryWidget>())
    {
        ParentInv->ClearHoveredItem(this);
    }
}

void UInventoryItemWidget::UpdateVisualSize(const FVector2D& CellSize)
{
    if (!Image) return;
    const int32 VX = bRotated ? SizeY : SizeX;
    const int32 VY = bRotated ? SizeX : SizeY;
    FSlateBrush Brush = Image->GetBrush();
    Brush.ImageSize = FVector2D(CellSize.X * VX, CellSize.Y * VY);
    Image->SetBrush(Brush);
}

void UInventoryItemWidget::SetTint(const FLinearColor& Color)
{
    if (Image)
    {
        Image->SetColorAndOpacity(Color);
    }
}


